import express from 'express';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
import { cloneStore, createDemoState } from './services/demo-data.js';
import { databaseStatus, initDatabase, saveDecision } from './db.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const app = express();
const port = Number(process.env.PORT || 3000);
const demo = createDemoState();
app.use(express.json({ limit: '256kb' }));
function runPython(command, payload = {}) {
  const result = spawnSync('python3', ['-m', 'ml.cli', command], { cwd: root, input: JSON.stringify(payload), encoding: 'utf8' });
  if (result.status !== 0) throw new Error(result.stderr || 'model process failed');
  return JSON.parse(result.stdout);
}
function referenceFeatures() {
  return { amount: 15000, sender_velocity: 6, receiver_velocity: 4, sender_fan_out_24h: 5, receiver_fan_in_24h: 4, cashout_flag: 0, new_relationship: 1, rapid_forwarding: 1, amount_vs_sender_avg: 5.7, hour: 2, account_age_days: 19, receiver_age_days: 25, device_changed: 0, merchant_flag: 0, channel: 'app' };
}
function demoSnapshot() {
  const snapshot = cloneStore(demo); const features = referenceFeatures();
  const prediction = runPython('prediction', features); const fraud = runPython('fraud', features); const explanation = runPython('explain', features); const impact = runPython('impact');
  snapshot.incident.nextMove = prediction; snapshot.incident.risk = Math.round(fraud.risk_score); snapshot.incident.confidence = fraud.fraud_probability;
  snapshot.incidents[0].risk = snapshot.incident.risk; snapshot.incidents[0].confidence = fraud.fraud_probability;
  snapshot.intervention.risk = snapshot.incident.risk; snapshot.intervention.cashout = Math.round(prediction.cashout * 100); snapshot.intervention.confidence = Math.round(fraud.fraud_probability * 100); snapshot.incident.explanation = explanation; snapshot.incident.evidence = [...snapshot.incident.evidence, ...explanation.evidence];
  snapshot.overview = impact.overview; snapshot.impact = impact;
  const created = snapshot.incident.timeline.find((x) => x.label === 'Incident created'); if (created) created.detail = `Risk engine scored flow at ${snapshot.incident.risk}/100 (calibrated P(fraud) ${fraud.fraud_probability})`;
  const auditRow = snapshot.audit.find((x) => x.entity === 'INC-2407'); if (auditRow) auditRow.detail = `Risk score ${snapshot.incident.risk} · suspected fraud`;
  snapshot.evaluation = runPython('evaluation'); return snapshot;
}


app.get('/_app/health', (req, res) => res.json({ ok: true, service: 'flowfreeze', mode: 'synthetic-demo', database: databaseStatus() }));
app.get('/api/health', (req, res) => res.json({ ok: true, database: databaseStatus() }));
app.get('/manus-routes.json', (req, res) => res.sendFile(path.join(root, 'frontend', 'public', 'manus-routes.json')));
app.get('/api/bootstrap', (req, res) => { try { res.json(demoSnapshot()); } catch (error) { res.status(503).json({ error: error.message }); } });
app.get('/api/overview', (req, res) => { try { res.json(runPython('impact').overview); } catch (error) { res.status(503).json({ error: error.message }); } });
app.get('/api/impact', (req, res) => { try { res.json(runPython('impact')); } catch (error) { res.status(503).json({ error: error.message }); } });
app.post('/api/explain', (req, res) => { try { res.json(runPython('explain', req.body || {})); } catch (error) { res.status(503).json({ error: error.message }); } });
app.get('/api/incidents', (req, res) => { try { res.json(demoSnapshot().incidents); } catch (error) { res.status(503).json({ error: error.message }); } });
app.get('/api/incidents/:id', (req, res) => { const incident = req.params.id === demo.incident.id ? demo.incident : demo.incidents.find((item) => item.id === req.params.id); incident ? res.json(incident) : res.status(404).json({ error: 'Incident not found' }); });
app.get('/api/transactions', (req, res) => res.json(demo.transactions));
app.get('/api/graph', (req, res) => res.json(demo.graph));
app.get('/api/wallets/:id', (req, res) => { const wallet = demo.wallets.find((item) => item.id === req.params.id); wallet ? res.json(wallet) : res.status(404).json({ error: 'Wallet not found' }); });
app.get('/api/predictions/:walletId', (req, res) => { try { const input = { ...referenceFeatures(), ...Object.fromEntries(Object.entries(req.query).filter(([key]) => key !== 'walletId')) }; if (input.amount) input.amount = Number(input.amount); for (const key of ['sender_velocity','receiver_velocity','cashout_flag','new_relationship','rapid_forwarding','account_age_days','device_changed','merchant_flag','hour']) if (input[key] !== undefined) input[key] = Number(input[key]); const prediction = runPython('prediction', input); res.json({ wallet: req.params.walletId, ...prediction, horizonMinutes: 5, explanation: 'Probability generated by the persisted next-move classifier from request features.' }); } catch (error) { res.status(503).json({ error: error.message }); } });
app.post('/api/fraud-score', (req, res) => { try { res.json(runPython('fraud', req.body || {})); } catch (error) { res.status(503).json({ error: error.message }); } });
app.get('/api/interventions', (req, res) => { try { res.json(demoSnapshot().intervention); } catch (error) { res.status(503).json({ error: error.message }); } });
app.get('/api/interventions/:id', (req, res) => res.json(demo.intervention));
app.post('/api/interventions/:id/decision', async (req, res) => { const { decision, reason, amount } = req.body || {}; if (!['approved', 'rejected', 'modified'].includes(decision) || !String(reason || '').trim()) return res.status(400).json({ error: 'decision and reason are required' }); demo.intervention.decision = decision; demo.intervention.reason = reason; demo.intervention.amount = Math.max(0, Math.min(Number(amount || demo.intervention.tainted), demo.intervention.balance)); demo.audit.unshift({ time: 'Just now', actor: 'Ayesha Rahman', action: `Intervention ${decision}`, entity: demo.intervention.id, detail: `${demo.intervention.scope} · ৳${demo.intervention.amount.toLocaleString('en-BD')}`, tone: decision === 'approved' ? 'mint' : 'coral' }); await saveDecision({ id: demo.intervention.id, walletId: demo.intervention.wallet, decision, amount: demo.intervention.amount, reason }).catch(() => false); res.json({ ok: true, intervention: demo.intervention, audit: demo.audit[0] }); });
app.get('/api/simulator', (req, res) => {
  const delay = Math.max(0, Number(req.query.delay || 0)); const hold = Math.max(25, Math.min(100, Number(req.query.hold || 68)));
  const edges = [{ sender_wallet: 'W4', receiver_wallet: 'W2', amount: 7000, minutes: 1 }, { sender_wallet: 'W4', receiver_wallet: 'AG-07', amount: 8000, minutes: 2, channel: 'agent' }, { sender_wallet: 'AG-07', receiver_wallet: 'CASH', amount: 8000, minutes: 3, is_cashout: true }];
  try { const result = runPython('simulation', { source: 'W4', delay_minutes: delay, hold_ratio: hold, initial_taint: 15000, edges }); const stages = result.stages; res.json({ delay, hold, preserved: stages.recoverable_amount_bdt, collateral: Math.max(0, 22000 - (22000 * hold / 100)), cashout: stages.cash_out_bdt, innocence: Math.max(0, 22000 - (22000 * hold / 100)), stages }); } catch (error) { res.status(503).json({ error: error.message }); }
});
app.get('/api/evaluation', (req, res) => { try { res.json(runPython('evaluation')); } catch (error) { res.status(503).json({ error: error.message }); } });
app.get('/api/audit', (req, res) => res.json(demo.audit));

app.get('/api/intelligence/health', async (req, res) => {
  const base = process.env.PYTHON_API_URL || 'http://127.0.0.1:8000';
  try { const response = await fetch(`${base}/health`); return res.status(response.status).json(await response.json()); }
  catch (error) { return res.json({ ok: true, service: 'flowfreeze-intelligence', mode: 'node-fallback', python_api: base, error: error.message, pipeline: ['synthetic/public data','feature & context layer','ML/AI engine','explanation / recommendation','operator action','measurable outcome','feedback loop'] }); }
});
app.post('/api/intelligence/recommend', async (req, res) => {
  const base = process.env.PYTHON_API_URL || 'http://127.0.0.1:8000';
  try { const response = await fetch(`${base}/api/v1/interventions/recommend`, { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${process.env.FLOWFREEZE_API_TOKEN || ''}` }, body: JSON.stringify(req.body) }); return res.status(response.status).json(await response.json()); }
  catch (error) { return res.status(503).json({ error: 'Trained intelligence API unavailable; no fallback prediction is returned.', detail: error.message }); }
});

app.use(express.static(path.join(root, 'dist')));
app.use('/frontend', express.static(path.join(root, 'frontend')));
app.use('/public', express.static(path.join(root, 'public')));
app.get('*', (req, res) => { if (req.path.startsWith('/api/')) return res.status(404).json({ error: 'API route not found' }); res.sendFile(path.join(root, 'dist', 'index.html'), (error) => { if (error) res.sendFile(path.join(root, 'index.html')); }); });

initDatabase().then(() => app.listen(port, '0.0.0.0', () => console.log(`FlowFreeze listening on 0.0.0.0:${port}`))).catch((error) => { console.error(error); process.exit(1); });
