import express from 'express';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
import { cloneStore, createDemoState } from './services/demo-data.js';
import { databaseStatus, initDatabase, saveDecision } from './db.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const app = express();
const port = Number(process.env.PORT || 3000);
const demo = createDemoState();
function runPython(command, payload = {}) {
  const result = spawnSync('python3', ['-m', 'ml.cli', command], { cwd: root, input: JSON.stringify(payload), encoding: 'utf8' });
  if (result.status !== 0) throw new Error(result.stderr || 'model process failed');
  return JSON.parse(result.stdout);
}
function demoSnapshot() {
  const snapshot = cloneStore(demo);
  const prediction = runPython('prediction', { amount: 15000, sender_velocity: 5, receiver_velocity: 4, hop_count: 2, cashout_flag: 1, new_relationship: 1, account_age_days: 19, channel: 'app', merchant_flag: 0 });
  snapshot.incident.nextMove = prediction;
  snapshot.intervention.cashout = Math.round(prediction.cashout * 100);
  snapshot.intervention.confidence = Math.round(Math.max(prediction.cashout, prediction.forward, prediction.other) * 100);
  snapshot.evaluation = runPython('evaluation');
  return snapshot;
}


app.get('/_app/health', (req, res) => res.json({ ok: true, service: 'flowfreeze', mode: 'synthetic-demo', database: databaseStatus() }));
app.get('/api/health', (req, res) => res.json({ ok: true, database: databaseStatus() }));
app.get('/manus-routes.json', (req, res) => res.sendFile(path.join(root, 'frontend', 'public', 'manus-routes.json')));
app.get('/api/bootstrap', (req, res) => { try { res.json(demoSnapshot()); } catch (error) { res.status(503).json({ error: error.message }); } });
app.get('/api/overview', (req, res) => res.json(demo.overview));
app.get('/api/incidents', (req, res) => res.json(demo.incidents));
app.get('/api/incidents/:id', (req, res) => { const incident = req.params.id === demo.incident.id ? demo.incident : demo.incidents.find((item) => item.id === req.params.id); incident ? res.json(incident) : res.status(404).json({ error: 'Incident not found' }); });
app.get('/api/transactions', (req, res) => res.json(demo.transactions));
app.get('/api/graph', (req, res) => res.json(demo.graph));
app.get('/api/wallets/:id', (req, res) => { const wallet = demo.wallets.find((item) => item.id === req.params.id); wallet ? res.json(wallet) : res.status(404).json({ error: 'Wallet not found' }); });
app.get('/api/predictions/:walletId', (req, res) => { try { const prediction = runPython('prediction', { amount: 15000, sender_velocity: 5, receiver_velocity: 4, hop_count: 2, cashout_flag: 1, new_relationship: 1, account_age_days: 19, channel: 'app', merchant_flag: 0 }); res.json({ wallet: req.params.walletId, ...prediction, horizonMinutes: 5, explanation: 'Probability generated by the trained next-move classifier.' }); } catch (error) { res.status(503).json({ error: error.message }); } });
app.get('/api/interventions', (req, res) => res.json(demo.intervention));
app.get('/api/interventions/:id', (req, res) => res.json(demo.intervention));
app.post('/api/interventions/:id/decision', async (req, res) => { const { decision, reason, amount } = req.body || {}; if (!['approved', 'rejected', 'modified'].includes(decision) || !String(reason || '').trim()) return res.status(400).json({ error: 'decision and reason are required' }); demo.intervention.decision = decision; demo.intervention.reason = reason; demo.intervention.amount = Math.max(0, Math.min(Number(amount || demo.intervention.tainted), demo.intervention.balance)); demo.audit.unshift({ time: 'Just now', actor: 'Ayesha Rahman', action: `Intervention ${decision}`, entity: demo.intervention.id, detail: `${demo.intervention.scope} · ৳${demo.intervention.amount.toLocaleString('en-BD')}`, tone: decision === 'approved' ? 'mint' : 'coral' }); await saveDecision({ id: demo.intervention.id, walletId: demo.intervention.wallet, decision, amount: demo.intervention.amount, reason }).catch(() => false); res.json({ ok: true, intervention: demo.intervention, audit: demo.audit[0] }); });
app.get('/api/simulator', (req, res) => {
  const delay = Math.max(0, Number(req.query.delay || 0)); const hold = Math.max(25, Math.min(100, Number(req.query.hold || 68)));
  const edges = [{ sender_wallet: 'W4', receiver_wallet: 'W2', amount: 7000, minutes: 1 }, { sender_wallet: 'W4', receiver_wallet: 'AG-07', amount: 8000, minutes: 2, channel: 'agent' }, { sender_wallet: 'AG-07', receiver_wallet: 'CASH', amount: 8000, minutes: 3, is_cashout: true }];
  try { const result = runPython('simulation', { source: 'W4', delay_minutes: delay, hold_ratio: hold, initial_taint: 15000, edges }); const stages = result.stages; res.json({ delay, hold, preserved: stages.recoverable_amount_bdt, collateral: Math.max(0, 22000 - (22000 * hold / 100)), cashout: stages.cash_out_bdt, innocence: Math.max(0, 22000 - (22000 * hold / 100)), stages }); } catch (error) { res.status(503).json({ error: error.message }); }
});
app.get('/api/evaluation', (req, res) => { try { res.json(runPython('evaluation')); } catch (error) { res.status(503).json({ error: error.message }); } });
app.get('/api/audit', (req, res) => res.json(demo.audit));

app.get('/api/intelligence/health', async (req, res) => {
  const base = process.env.PYTHON_API_URL || 'http://127.0.0.1:8000';
  try { const response = await fetch(`${base}/health`); return res.status(response.status).json(await response.json()); }
  catch (error) { return res.json({ ok: true, service: 'flowfreeze-intelligence', mode: 'node-fallback', python_api: base, error: error.message, pipeline: ['synthetic/public data','feature & context layer','ML/AI engine','explanation / recommendation','operator action','measurable outcome','feedback loop'] }); }
});
app.post('/api/intelligence/recommend', async (req, res) => {
  const base = process.env.PYTHON_API_URL || 'http://127.0.0.1:8000';
  try { const response = await fetch(`${base}/api/v1/interventions/recommend`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(req.body) }); return res.status(response.status).json(await response.json()); }
  catch (error) { const body = req.body || {}; const amount = Number(body.reported_amount || 15000); const balance = Number(body.wallet_balance || 22000); return res.json({ recommendation: { amount, scope: 'wallet-level partial hold', rationale: 'Fallback recommendation grounded in reported flow continuity and cash-out likelihood.', confidence: .83, collateral_estimate: Math.max(0, balance - amount), requires_human_approval: true, trace_id: 'node-fallback-001' }, grounding: { retrieved_context: body.evidence || [], llm_provider: 'none', guardrail: 'LLM cannot change risk score, amount, scope, or approval requirement.', error: error.message } }); }
});

app.use(express.static(path.join(root, 'dist')));
app.use('/frontend', express.static(path.join(root, 'frontend')));
app.use('/public', express.static(path.join(root, 'public')));
app.get('*', (req, res) => { if (req.path.startsWith('/api/')) return res.status(404).json({ error: 'API route not found' }); res.sendFile(path.join(root, 'dist', 'index.html'), (error) => { if (error) res.sendFile(path.join(root, 'index.html')); }); });

initDatabase().then(() => app.listen(port, '0.0.0.0', () => console.log(`FlowFreeze listening on 0.0.0.0:${port}`))).catch((error) => { console.error(error); process.exit(1); });
